// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using NeuroTrack.Data;

#nullable disable

namespace NeuroTrack.Migrations
{
    [DbContext(typeof(NeuroTrackDbContext))]
    partial class NeuroTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NeuroTrack.Models.TestResult", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Badge").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<DateTime>("Date").HasColumnType("datetime2");
                b.Property<double>("FocusScore").HasColumnType("float");
                b.Property<string>("Level").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<double>("MemoryScore").HasColumnType("float");
                b.Property<double>("OverallScore").HasColumnType("float");
                b.Property<double>("ReactionTime").HasColumnType("float");
                b.Property<int>("XP").HasColumnType("int");

                b.HasKey("Id");
                b.ToTable("TestResults");
            });
#pragma warning restore 612, 618
        }
    }
}
